version: '3'

services:
  app:
    image: warehousemanagement
    restart: always
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27107:27107"